<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ns2:test-suite xmlns:ns2="urn:model.allure.qatools.yandex.ru" start="1447310363509" stop="1447310430375">
    <name>Smoke-Test-Suite</name>
    <test-cases>
        <test-case start="1447310363544" stop="1447310374818" status="passed">
            <name>checkTutorLogin[nukesh.smts@gmail.com,123]</name>
            <steps>
                <step start="1447310363544" stop="1447310374814" status="passed">
                    <name>checkTutorLogin</name>
                    <title>Tuorlogin Enter email, password</title>
                    <attachments/>
                    <steps/>
                </step>
            </steps>
            <attachments/>
            <labels/>
        </test-case>
        <test-case start="1447310374818" stop="1447310430355" status="failed">
            <name>checkTutorLogout</name>
            <failure>
                <message>AssertionError: Time out exception is occurred</message>
                <stack-trace>java.lang.AssertionError: Time out exception is occurred
	at com.diw.action.UserActions.getWebElement(UserActions.java:54)
	at com.diw.action.UserActions.click(UserActions.java:100)
	at com.diw.page.TutorProfile.doTutorLogout(TutorProfile.java:16)
	at com.diw.test.TutorLoginPageTest.checkTutorLogout(TutorLoginPageTest.java:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:293)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:91)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
</stack-trace>
            </failure>
            <steps>
                <step start="1447310374822" stop="1447310430026" status="failed">
                    <name>checkTutorLogout</name>
                    <title>Tutor Logout</title>
                </step>
            </steps>
            <attachments>
                <attachment title="Screen_Shot" source="10783cd36c6729bf12f97f94d02331344f9fd6d0b1adb16c0326e18e24f889b9-attachment.png" type="image/png" size="24090"/>
            </attachments>
            <labels/>
        </test-case>
    </test-cases>
    <labels/>
</ns2:test-suite>
